### PR TITLE
Added COUNT parameter to options

### PR DESCRIPTION
**Pull request by igorolhovskiy**

### CODE REVIEW

**Comment by ncopa** [comment]
I don't understand what problem this is supposed to solve?

**Comment by igorolhovskiy** [comment]
Idea is to have a list of same parameters.
Like if I want to pass some patterns over command line. And specify like:
... -p 123 -p 321 ...
So we will have opts.p = {1 => 123, 2 => 321}

**Comment by ncopa** [comment]
I don't think we should use a `C` for collecting arguments to the options in a table. It may give unexpected consequences for things like:
```
 -c, --command=COMMAND     specify the command to execute
 -d, --dir=DIR             specify directory ...
```
In this case the `command` would be a table with an array of collected commands, wile `dir` would only contain the last specified dir `--command=foo --command=bar, --dir=first, --dir=second`.

I think we can either have a global flag to tell that the opt args should be collected in an array. Maybe something like:
```Lua
local optarg=require('optarg')
optarg.multiargs=true
opthelp = [[
 -p NUM      number of p something
]]
```

Would collect `... -p 123 -p 321` into `p = {[1]='123',[2]='321'}` when `optarg.multiargs` is set to true and would return the last, `p = '321'` when its false (default and current behavior).

**Comment by ncopa** [comment]
should be fixed in https://github.com/ncopa/lua-optarg/commit/de33b5ab216566b53d57131eb615ee18cb94a888

**Pull request closed without merging**
